```{r}
library(imputeTS)
library(lubridate)
library(dplyr)
library(readxl)
library(tidyr)
library(readr)
```
# Functions

```{r}
interpolate <- function(df_small, first_day, last_day) {
  
  days = seq(first_day, last_day, by = "days")

  df1 <- data.frame("fecha" = days)
  
  df <- left_join(df1, df_small, by = "fecha")

  df_int <- df |> 
  select(-fecha) |>  
  apply(MARGIN = 2, FUN = as.numeric)|> 
  apply(MARGIN = 2, FUN = na_interpolation)
  
  df_int <- as.data.frame(df_int)
  
  df_int["fecha"] = df1["fecha"]
  
  weeks_date <- seq(first_day, last_day, by = "week")
  
  df_filter_weeks <- df_int %>% 
  filter(fecha %in% weeks_date) %>% 
  select(1:ncol(df_int))
  
  df_filter_weeks <- df_filter_weeks |> 
  mutate(year = isoyear(fecha)) |> 
  filter(year %in% c(2020, 2021, 2022, 2023, 2024, 2025)) |> 
  mutate(week1 = isoweek(fecha)) |> 
  mutate(week = paste(year, week1, sep = "-")) |> 
  filter(week != "2021-53") |> 
  filter(week != "2020-53") |> 
  filter(week != "2022-53") |> 
  filter(week != "2023-53") |>
  filter(week != "2024-53") |>
  filter(week != "2025-53") |> 
  select(-c(fecha, year, week1))
  
  return(df_filter_weeks)
}
```

```{r}
canton_week <- function(df, var_name) {
  df_pivot = pivot_longer(df, cols = -c("week"), names_to = "code", values_to = var_name)
df_pivot <- df_pivot |> 
  mutate(week_canton = paste(week, code, sep = "-")) |> 
  select(week_canton, var_name)
  return(df_pivot)
}
```

# Population

```{r}
pobs = read_excel("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/pob_anual.xlsx")
```
```{r}
pobs_t = t(pobs)
```

```{r}
pobs_t = data.frame(pobs_t)
colnames(pobs_t) = pobs_t[1,1:ncol(pobs_t)]
pobs_t = pobs_t[-c(1, 2, 11, 12, 13), 1:ncol(pobs_t)]
```

```{r}
pobs_t["fecha"] <- c(ymd("2019-06-30"), ymd("2020-06-30"), ymd("2021-06-30"), ymd("2022-06-30"), ymd("2023-06-30"), ymd("2024-06-30"), ymd("2025-06-30"), ymd("2026-06-30"))
```
```{r}
pobs_t
```

```{r}
pob_int <- interpolate(pobs_t, ymd("2019-06-30"), ymd("2026-06-30"))
```

```{r}
write.csv(pob_int, "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/pob_int_rr.csv")
```

```{r}
colnames(baseLST_int)
```

```{r}
pob_int_0 <- pob_int |> select(-c("  0", "612", "613"))
pob_pivot <- canton_week(pob_int_0, var_name = "pob")
```

```{r}
write.csv(pob_pivot, "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/clean/pob_int.csv")
```

# NDVI

```{r}
baseNDVI <- read.csv("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/baseNDVI.csv")
baseNDVI <- baseNDVI |> 
  mutate(fecha = ymd(fecha)) |> 
  select(ndvi, fecha, ID)
```

```{r}
baseNDVI_wide <- pivot_wider(baseNDVI, names_from = ID, values_from =  ndvi)
```

```{r}
baseNDVI_wide
```



```{r}
baseNDVI_int <- interpolate(baseNDVI_wide, first_day = ymd("2020-01-01"), last_day = ymd("2026-01-01"))
```

```{r}
baseNDVI_pivot <- canton_week(baseNDVI_int, var_name = "ndvi")
```

```{r}
write.csv(baseNDVI_pivot, "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/clean/NDVI_int.csv")
```

# LST

```{r}
baseLST <- read.csv("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/baseLST.csv")
baseLST <- baseLST |> 
  mutate(fecha = ymd(fecha)) |> 
  select(lst, fecha, ID)
```

```{r}
baseLST_wide <- pivot_wider(baseLST, names_from = ID, values_from =  lst)
```

```{r}
baseLST_wide
```
```{r}
baseLST_int <- interpolate(baseLST_wide, first_day = ymd("2020-01-01"), last_day = ymd("2025-12-31"))
```

```{r}
baseLST_pivot <- canton_week(baseLST_int, var_name = "lst")
```

```{r}
write.csv(baseLST_pivot, "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/clean/LST_int.csv")
```


# El Niño

## SST

```{r}
baseSST1 <-
  read_table('https://www.cpc.ncep.noaa.gov/data/indices/ersst5.nino.mth.91-20.ascii')
```
```{r}
baseSST1 <- baseSST1 |> 
  filter(YR %in% seq(2020, 2025)) |> 
  mutate(MON1 = case_when(MON == 1 ~ "01", 
                          MON == 2 ~ "02", 
                          MON == 3 ~ "03", 
                          MON == 4 ~ "04",
                          MON == 5 ~ "05",
                          MON == 6 ~ "06", 
                          MON == 7 ~ "07", 
                          MON == 8 ~ "08",
                          MON == 9 ~ "09",
                          MON == 10 ~ "10", 
                          MON == 11~ "11",
                          MON == 12 ~ "12"))
baseSST1 <- baseSST1 |> 
  mutate(fecha1 = paste(YR, MON1, "15", sep = "-")) |> 
  mutate(fecha = ymd(fecha1)) |> 
  select(fecha = fecha,
         nino12ssta = ANOM,
         nino3ssta = ANOM_1,
         nino4ssta = ANOM_2,
         nino34ssta = ANOM_3)
```

```{r}
baseSST_int <- interpolate(baseSST1, first_day = ymd("2020-01-01"), last_day =  ymd("2026-12-31"))
```

```{r}
baseSST_int
```

```{r}
nino12 <- baseSST_int |> 
  select(week, nino12ssta)

nino3 <- baseSST_int |> 
  select(week, nino3ssta)

nino4 <- baseSST_int |> 
  select(week, nino4ssta)
```

```{r}
codes <- read_excel("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/dengue_limpio.xlsx")

codes <- codes |> 
  select(ID, "PROVINCIA Y CANTON") |> 
  filter(ID >= 101)

colnames(codes) = c("ID", "site1")

cantones <- codes["ID"]

cantones_vector <- cantones[[1]]

cantones_vector = as.character(cantones_vector)
```

```{r}
nino12[cantones_vector] <- nino12$nino12ssta

nino12 <- nino12 |> 
  select(-c(nino12ssta))

nino3[cantones_vector] <- nino3$nino3ssta

nino3 <- nino3 |> 
  select(-c(nino3ssta))

nino4[cantones_vector] <- nino4$nino4ssta

nino4 <- nino4 |> 
  select(-c(nino4ssta)) 
```

```{r}
nino12_pivot <- canton_week(df = nino12, var_name = "nino12ssta") 

nino3_pivot <- canton_week(df = nino3, var_name = "nino3ssta")

nino4_pivot <- canton_week(df = nino4, var_name = "nino4ssta")
```

```{r}
baseSST <- left_join(nino12_pivot, nino3_pivot, by = "week_canton")
```

```{r}
write.csv(baseSST_pivot, "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/clean/SST_int.csv")
```


## TNA

```{r}
datosTNA1 <-
  read_table(
    'https://www.esrl.noaa.gov/psd/data/correlation/tna.data'
  )
```

```{r}
baseSST1 <- baseSST1 |> 
  filter(YR %in% seq(2020, 2025)) |> 
  mutate(MON1 = case_when(MON == 1 ~ "01", 
                          MON == 2 ~ "02", 
                          MON == 3 ~ "03", 
                          MON == 4 ~ "04",
                          MON == 5 ~ "05",
                          MON == 6 ~ "06", 
                          MON == 7 ~ "07", 
                          MON == 8 ~ "08",
                          MON == 9 ~ "09",
                          MON == 10 ~ "10", 
                          MON == 11~ "11",
                          MON == 12 ~ "12"))
baseSST1 <- baseSST1 |> 
  mutate(fecha1 = paste(YR, MON1, "15", sep = "-")) |> 
  mutate(fecha = ymd(fecha1)) |> 
  select(c(fecha, ANOM, ANOM_1, ANOM_2, ANOM_3))
```

```{r}
baseSST_int <- interpolate(baseSST1, first_day = ymd("2020-01-01"), last_day =  ymd("2026-12-31"))
```

```{r}
baseSST_int
```

