This file calculates the 8th week lags for each variable.

```{r}
library(dplyr)
library(tidyr)
library(stringr)
```
# Functions 

```{r}
separate_canton <- function(df, var) {
  
  # Function that takes a dataframe with week-canton pairs as rows and returns a dataframe with cantons as columns and weeks as rows

  # Parameters
  #  ----
  #  df: dataframe
  #    a dataframe with variables as columns and the week-canton pairs as rows

  #  var: string
  #    variable that will be contained in the cells of df_long

  #  Returns
  #  ----
  #  df_long: a dataframe with the weeks as rows and the cantons as columns
  
  df_long <- df |> 
  mutate(canton = str_extract(week_canton, "[^-]+$")) |> 
  mutate(week = str_extract(week_canton, "^[^-]*-[^-]*")) |> 
  select(-week_canton) |> 
  pivot_wider(id_cols = week, names_from = canton, values_from = var)
  
  #return(df_long)
}

lags <- function(df, n, var){
  
  # Function that 

  # Parameters
  #  ----
  #  df: dataframe
  #    

  #  n: int
  #    the value will be calculated for the nth week before the current week

  #  var: string
  #   variable whose nth lag will be calculated

  #  Returns
  #  ----
  #  df_lag: a dataframe with the nth week lag for var for each canton. each column has the format canton_var_lag_n
  
  df_lag = df
  for (i in 1:length(colnames(df))) {
    columna = colnames(df)[i]
    if (columna == "week") {
      next
    }
    df_lag[paste(columna, var, "lag", as.character(n), sep = "_")] = lag(df[columna], n)
    df_lag <- df_lag |> 
      select(-columna)
  }
  return(df_lag)
}

week_canton_fun <- function(df) {
  
  # Function that converts a dataframe from wide to long with rows as week-canton pairs and a single column which corresponds to the lagged variable

  # Parameters
  #  ----
  #  df: dataframe
  #    dataframe in which each column has the format canton_var_lag_n and the rows are the week

  #  Returns
  #  ----
  #  df_wk: dataframe with rows as week-canton pairs and a single column which corresponds to the lagged variable
  
  df_wk <- df |> 
  drop_na() |> 
  pivot_longer(cols = 2:ncol(df)) |> 
  mutate(canton = str_extract(name, "^[^_]+")) |> 
  mutate(var = str_extract(name, "(?<=^[^_]{0,100}_).*")) |> 
  mutate(week_canton = paste(week, canton, sep = "-")) |> 
  select(week_canton, var, value) |> 
  pivot_wider(id_cols = week_canton, names_from = var, values_from = value)
  
  return(df_wk)
}

calculate_lags <- function(df, var, n) {

  # Function that transforms a dataframe with variable values as columns and week-canton pairs as rows and returns a dataframe with week-canton pairs as rows and a single column that corresponds to the nth week lag of the selected variable

  # Parameters
  #  ----
  #  df: dataframe
  #    dataframe with variable values as columns and week-canton pairs as rows

  #  n: int
  #    the resulting lag will be the nth week before the current week

  #  var: string
  #   variable whose nth lag will be calculated

  #  Returns
  #  ----
  #  df_lags: dataframe with week-canton pairs as rows and a single column that corresponds to the nth week lag of the selected variable
  
  df_lags <- week_canton_fun(lags(separate_canton(df, var), n, var))
  return(df_lags)
}

lag_8_df <- function(df, var) {
  
  # Function that returns the lag for 1-8 weeks before the current week

  # Parameters
  #  ----
  #  df: dataframe
  #    dataframe for lag calculation (week-canton pairs as rows and var or vars as columns)

  #  var: string
  #    variable whose lags will be calculated

  #  Returns
  #  ----
  #  df_pivot: dataframe with week-canton pairs as rows and the 8 lags of the chosen variable
  
  df_lag_1 <- calculate_lags(df, var, 1)
  df_lag_2 <- calculate_lags(df, var, 2)
  df_lag_3 <- calculate_lags(df, var, 3)
  df_lag_4 <- calculate_lags(df, var, 4)
  df_lag_5 <- calculate_lags(df, var, 5)
  df_lag_6 <- calculate_lags(df, var, 6)
  df_lag_7 <- calculate_lags(df, var, 7)
  df_lag_8 <- calculate_lags(df, var, 8)
  
  df_lags <- df_lag_8 |>  
    left_join(df_lag_7, by = "week_canton") |> 
    left_join(df_lag_6, by = "week_canton") |> 
    left_join(df_lag_5, by = "week_canton") |>  
    left_join(df_lag_4, by = "week_canton")|>  
    left_join(df_lag_3, by = "week_canton")|>  
    left_join(df_lag_2, by = "week_canton")|>  
    left_join(df_lag_1, by = "week_canton")
}
  
```

# Casos 

```{r}
casos <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\casos_dengue.csv)")

colnames(casos)[which(colnames(casos) == "week.canton")] = "week_canton"
```

```{r}
# Delete total (country and provinces), unknown and foreign cases
casos_long <- separate_canton(casos, "casos") |> 
  select(-c("0", "1", "2", "3", "4", "5", "6", "7", "98", "99"))
```

```{r}
# Because casos_long has weeks as rows, it can't be calculated with lag_8_df
casos_lag_1 <- week_canton_fun(lags(casos_long, 1, "casos"))
casos_lag_2 <- week_canton_fun(lags(casos_long, 2, "casos"))
casos_lag_3 <- week_canton_fun(lags(casos_long, 3, "casos"))
casos_lag_4 <- week_canton_fun(lags(casos_long, 4, "casos"))
casos_lag_5 <- week_canton_fun(lags(casos_long, 5, "casos"))
casos_lag_6 <- week_canton_fun(lags(casos_long, 6, "casos"))
casos_lag_7 <- week_canton_fun(lags(casos_long, 7, "casos"))
casos_lag_8 <- week_canton_fun(lags(casos_long, 8, "casos"))
```

```{r}
casos_lags <- casos_lag_8 |> 
  left_join(casos_lag_7, by = "week_canton") |> 
  left_join(casos_lag_6, by = "week_canton") |> 
  left_join(casos_lag_5, by = "week_canton") |> 
  left_join(casos_lag_4, by = "week_canton") |> 
  left_join(casos_lag_3, by = "week_canton") |> 
  left_join(casos_lag_2, by = "week_canton") |> 
  left_join(casos_lag_1, by = "week_canton")
```

```{r}
write.csv(casos_lags, r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\lags\casos_dengue_lags.csv)")
```

# Riesgo relativo

```{r}
rr_num <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\relative_risk.csv)") |> 
  select(rr, week.canton)

colnames(rr_num)[which(colnames(rr_num) == "week.canton")] = "week_canton"

rr_clasi <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\relative_risk.csv)") |> 
  select(clasi_rr, week.canton)

colnames(rr_clasi)[which(colnames(rr_clasi) == "week.canton")] = "week_canton"

rr_clasi_no_0 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\relative_risk.csv)") |> 
  select(clasi_rr_no_0, week.canton)

colnames(rr_clasi_no_0)[which(colnames(rr_clasi_no_0) == "week.canton")] = "week_canton"
```

```{r}
rr_num_lag <- lag_8_df(rr_num, "rr")
rr_clasi_lag <- lag_8_df(rr_clasi, "clasi_rr")
rr_clasi_no_0_lag <- lag_8_df(rr_clasi_no_0, "clasi_rr_no_0")
```

```{r}
rr_lags <- left_join(rr_num_lag, rr_clasi_lag, by = "week_canton") |> 
  left_join(rr_clasi_no_0_lag, by = "week_canton") 
```

```{r}
write.csv(rr_lags, r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\lags\relative_risk_lags.csv)")
```

# Tmax

```{r}
tmax_mean <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\tmax_weekly.csv)") |> 
  select(week_canton, tmax_mean)
```

```{r}
tmax_mean_lag <- lag_8_df(tmax_mean, "tmax_mean")
```

```{r}
write.csv(tmax_mean_lag, r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\lags\tmax_lags.csv)")
```

# Tmin

```{r}
tmin_mean <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\tmin_weekly.csv)") |> 
  select(week_canton, tmin_mean)
```

```{r}
tmin_mean_lag <- lag_8_df(tmin_mean, "tmin_mean")
```

```{r}
write.csv(tmin_mean_lag, r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\lags\tmin_lags.csv)")
```

# Temp_prom

```{r}
temp_prom <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\temp_prom.csv)") |> 
  select(week_canton, temp_prom)
```

```{r}
temp_prom_lag <- lag_8_df(temp_prom, "temp_prom")
```

```{r}
write.csv(temp_prom_lag, r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\lags\temp_prom_lags.csv)")
```

# CHIRPS

```{r}
precip_total <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\precip_weekly.csv)") |> 
  select(week_canton, precip_total) 

precip_min <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\precip_weekly.csv)") |> 
  select(week_canton, precip_min) 

precip_max <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\precip_weekly.csv)") |> 
  select(week_canton, precip_max)

precip_mean <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\precip_weekly.csv)") |> 
  select(week_canton, precip_mean)

precip_median<- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\precip_weekly.csv)") |> 
  select(week_canton, precip_median)
```

```{r}
precip_total_lag <- lag_8_df(precip_total, "precip_total")
precip_max_lag <- lag_8_df(precip_max, "precip_max")
precip_mean_lag <- lag_8_df(precip_mean, "precip_mean")
precip_median_lag <- lag_8_df(precip_median, "precip_median")
precip_min_lag <- lag_8_df(precip_min, "precip_min")
```

```{r}
precip_lags <- left_join(precip_total_lag, precip_max_lag, by = "week_canton") |> 
  left_join(precip_mean_lag, by = "week_canton") |> 
  left_join(precip_median_lag, by = "week_canton") |>
  left_join(precip_min_lag, by = "week_canton") 
```

```{r}
write.csv(precip_lags, r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\lags\precip_lags.csv)")
```

# Trends

```{r}
trends_1 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, aedes_aegypti = aedes_aegypti)

trends_2 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, criaderos_de_mosquito)

trends_3 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, fiebre)

trends_4 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, plaquetas)

trends_5 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, buscar_trabajo)

trends_6 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, desempleo)

trends_7 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, empleo)

trends_8 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, comprar_carro)

trends_9 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, préstamo)

trends_10 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, tiquetes_avion)

trends_11 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, vacaciones)

trends_12 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, corte_agua)

trends_13 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, corte_de_agua)

trends_14 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, suspension_de_agua)

trends_15 <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\trends_keywords.csv)") |> 
  select(week_canton, dengue)
```

```{r}
trends_1_lag <- lag_8_df(trends_1, "aedes_aegypti")
trends_2_lag <- lag_8_df(trends_2, "criaderos_de_mosquito")
trends_3_lag <- lag_8_df(trends_3, "fiebre")
trends_4_lag <- lag_8_df(trends_4, "plaquetas")
trends_5_lag <- lag_8_df(trends_5, "buscar_trabajo")
trends_6_lag <- lag_8_df(trends_6, "desempleo")
trends_7_lag <- lag_8_df(trends_7, "empleo")
trends_8_lag <- lag_8_df(trends_8, "comprar_carro")
trends_9_lag <- lag_8_df(trends_9, "préstamo")
trends_10_lag <- lag_8_df(trends_10, "tiquetes_avion")
trends_11_lag <- lag_8_df(trends_11, "vacaciones")
trends_12_lag <- lag_8_df(trends_12, "corte_agua")
trends_13_lag <- lag_8_df(trends_13, "corte_de_agua")
trends_14_lag <- lag_8_df(trends_14, "suspension_de_agua")
trends_15_lag <- lag_8_df(trends_15, "dengue")
```

```{r}
trends_lags <- left_join(trends_1_lag, trends_2_lag, by = "week_canton") |> 
  left_join(trends_3_lag, by = "week_canton") |> 
  left_join(trends_4_lag, by = "week_canton") |> 
  left_join(trends_5_lag, by = "week_canton") |> 
  left_join(trends_6_lag, by = "week_canton") |> 
  left_join(trends_7_lag, by = "week_canton") |> 
  left_join(trends_8_lag, by = "week_canton") |> 
  left_join(trends_9_lag, by = "week_canton") |> 
  left_join(trends_10_lag, by = "week_canton") |> 
  left_join(trends_11_lag, by = "week_canton") |> 
  left_join(trends_12_lag, by = "week_canton") |> 
  left_join(trends_13_lag, by = "week_canton") |> 
  left_join(trends_14_lag, by = "week_canton")|> 
  left_join(trends_15_lag, by = "week_canton")
```

```{r}
write.csv(trends_lags, r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\lags\trends_keywords_lags.csv)")
```

# SST

```{r}
sst <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\SST_int.csv)") |> 
  select(week_canton, nino34ssta)
```

```{r}
sst_lags <- lag_8_df(sst, "nino34ssta")
```

```{r}
write.csv(sst_lags, r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\lags\sst_lags.csv)")
```

# NDVI

```{r}
ndvi <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\NDVI_int.csv)") |> 
  select(week_canton, ndvi)
```

```{r}
ndvi_lags <- lag_8_df(ndvi, "ndvi")
```

```{r}
write.csv(ndvi_lags, r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\interim\lags\NDVI_lags.csv)")
```