```{r}
library(dplyr)
library(lubridate)
```

```{r}
campa_raw <- read.csv(r"(C:\Users\nan\OneDrive - Universidad de Costa Rica\cuenta personal\ucr pers\practica profesional\practica dengue\dengue-model\data\raw\campanas_raw.csv)")
```

```{r}
campa_raw <- campa_raw |> 
  select(-c(Distrito, Link, Conteo)) |> 
  mutate(mes_num = case_when(Mes == 1 ~ "01",
                             Mes == 2 ~ "02",
                             Mes == 3 ~ "03", 
                             Mes == 4 ~ "04",
                             Mes == 5 ~ "05",
                             Mes == 6 ~ "06",
                             Mes == 7 ~ "07",
                             Mes == 8 ~ "08",
                             Mes == 9 ~ "09",
                             Mes == 10 ~ "10",
                             Mes == 11 ~ "11",
                             Mes == 12 ~ "12")) |> 
  mutate(dia = case_when(Dia == 1 ~ "01",
                             Dia == 2 ~ "02",
                             Dia == 3 ~ "03", 
                             Dia == 4 ~ "04",
                             Dia == 5 ~ "05",
                             Dia == 6 ~ "06",
                             Dia == 7 ~ "07",
                             Dia == 8 ~ "08",
                             Dia == 9 ~ "09",
                             Dia == 10 ~ "10",
                             Dia == 11 ~ "11",
                             Dia == 12 ~ "12")) |> 
  mutate(annio = as.character(Año)) |> 
  mutate(mes_annio = paste(Año, mes_num, sep = "-")) |> 
  select(c(tipo = Tipo.de.Campaña,
           canton = Canton,
           dia,
           mes_annio, 
           annio)) |> 
  mutate(fecha1 = paste(mes_annio, as.character(dia), sep = "-")) |> 
  mutate(fecha = ymd(fecha1)) |> 
  select(-fecha1) |> 
  mutate(week1 = isoweek(fecha)) |> 
  mutate(week = paste(annio, week1, sep = "-")) |> 
  select(-c(annio, week1))


```

```{r}
# Use canton code instead of canton name
codes <- read_excel("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/dengue_limpio.xlsx")

codes <- codes |> 
  select(ID, canton2 = "PROVINCIA Y CANTON") |> 
  filter(ID >= 101)

campa_raw <- campa_raw |> 
  mutate(canton1 = toupper(canton)) |> 
  mutate(canton2 = chartr("áéíóúñÁÉÍÓÚ", "aeiounAEIOU", canton1)) |> 
  select(-canton1)
```

```{r}
campa <- left_join(campa_raw, codes, by = "canton2") |> 
  select(-c(canton2))
```

```{r}
write.csv(campa, "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/campaigns_eda.csv")
```




