```{r}
library(lubridate)
library(dplyr)
library(readxl)
```

```{r}
setwd("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/chirps")

precip <- read.csv(file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/chirps/chirps_precip.csv")
```

```{r}
precip$time = ymd(precip$time)
```

```{r}
precip
```

```{r}
precip |> group_by(canton) |> 
  summarise(nulos = sum(is.na(precip)), 
            total_obs = n())
```

```{r}
precip |> group_by(canton, longitude, latitude) |> 
  summarise(nulos = sum(is.na(precip)), 
            total_obs = n(),
            .groups = "drop") |> 
  filter(nulos > 0)
```


```{r}
precip_weekly_site <- precip |> 
  mutate(year = isoyear(time)) |> 
  mutate(week1 = isoweek(time)) |>
  group_by(week1, year, canton) |> 
  summarise(precip_total = sum(precip),
            precip_min = min(precip), 
            precip_max = max(precip),
            precip_mean = mean(precip),
            precip_median = median(precip),
    .groups = "drop" ) |> 
  mutate(week = paste(year, week1, sep = "-")) |> 
  filter(!grepl("-53$", week))
```
```{r}
precip_weekly_site
```
```{r}
codes <- read_excel("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/dengue_limpio.xlsx")

codes <- codes |> 
  select(ID, "PROVINCIA Y CANTON") |> 
  filter(ID >= 101)

colnames(codes) = c("ID", "site1")
```

```{r}
codes[11, "site1"] = "VAZQUEZ DE CORONADO"
codes[20, "site1"] = "LEON CORTES CASTRO"
codes[31, "site1"] = "ZARCERO"
codes[32, "site1"] = "SARCHI"
```


```{r}
precip_weekly_site <- precip_weekly_site |> 
  mutate(site2 = toupper(canton)) |> 
  mutate(site1 = chartr("áéíóúñÁÉÍÓÚ", "aeiounAEIOU", site2))
```

```{r}
precip_weekly <- left_join(precip_weekly_site, codes, by = "site1") |> 
  select(-c(year, week1, canton, site1, site2))
```

```{r}
precip_weekly # No hay datos a partir de la semana 41 del 2025
```
```{r}
para_eda <- function(df, var) {
  df_new <- df |> 
    select(c(week, ID, var)) |>
    pivot_wider(names_from = ID, values_from = var, id_cols = week)
  write.csv(df_new, file = paste0("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/", var, "_eda.csv"))
}
```

```{r}
para_eda(precip_weekly, precip_total)

para_eda(precip_weekly, precip_min)

para_eda(precip_weekly, precip_max)

para_eda(precip_weekly, precip_mean)

para_eda(precip_weekly, precip_median)
```


```{r}
write.csv(precip_total, file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/precip_total_eda.csv")

write.csv(precip_min, file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/precip_min_eda.csv")

write.csv(precip_max, file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/precip_max_eda.csv")

write.csv(precip_mean, file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/precip_mean_eda.csv")

write.csv(precip_median, file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/precip_median_eda.csv")
```


```{r}
precip_weekly <- precip_weekly  |> 
  mutate(week_canton = paste(week, ID, sep = "-")) |> 
  select(-c(ID, week))
```
```{r}
precip$week
```

```{r}
52*6*82 - 24600
```
```{r}
precip_weekly
```


```{r}
write.csv(precip_weekly, file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/clean/precip_weekly.csv")
```






