This file aggregates CHIRTS min and max temperature data weekly using their means. Then, it imputes Golfito using IDW. Additionally, it creates the average weekly temperature data.

```{r}
library(lubridate)
library(dplyr)
library(tidyr)
library(readxl)
library(sf)
library(gstat)
```

```{r}
para_eda <- function(df, var) {
#  Function that saves a csv file to be used in the EDA report. 

# Parameters
#  ----
#  df: dataframe
#    Data that contains the week and canton codes as columns

#  var: string
#    Variable that will fill the cells in the dataframe. For example, if the variable is "mean," the resulting dataframe from this function will contain the data for the mean.

#  Returns
#  ----
#  Nothing, just saves df_new (the generated dataframe with weeks as rows and canton codes as columns) in a csv file for eda purposes
  
  df_new <- df |> 
    select(c(week, ID, var)) |>
    pivot_wider(names_from = ID, values_from = var, id_cols = week)
  write.csv(df_new, file = paste0("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/", var, "_eda.csv"))
}
```

## Temp max

```{r}
setwd("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/chirts/chirts_max")

tmax <- read.csv(file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/chirts/chirts_max/chirts_max.csv")
```

```{r}
colnames(tmax)
```

```{r}
tmax$time = ymd(tmax$time)
```

```{r}
# Aggregate tmax weekly with mean
tmax_weekly_site <- tmax |> 
  group_by(canton, year = isoyear(time), week1 = isoweek(time)) |>
  summarise(tmax_mean = mean(temp),
    .groups = "drop" )  |> 
  mutate(week = paste(year, week1, sep = "-")) |> 
  filter(!grepl("-53$", week)) |> 
  filter(!grepl("2026", week))
```

```{r}
# Load file that contains canton names and codes to add canton codes to tmax database
codes <- read_excel("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/dengue_limpio.xlsx")

codes <- codes |> 
  select(ID, "PROVINCIA Y CANTON") |> 
  filter(ID >= 101)

colnames(codes) = c("ID", "canton")

codes[11, "canton"] = "VAZQUEZ DE CORONADO"
codes[20, "canton"] = "LEON CORTES CASTRO"
codes[31, "canton"] = "ZARCERO"
codes[32, "canton"] = "SARCHI"
```

```{r}
# Standardize canton name in dataset so it is ready to be merged
tmax_weekly_site <- tmax_weekly_site |> 
   mutate(canton = toupper(canton)) |> 
   mutate(canton = chartr("áéíóúñÁÉÍÓÚ", "aeiounAEIOU", canton)) 
```

```{r}
# Add latitude and longitude so the data can be imputed spatially
tmax_lon <- tmax[!duplicated(tmax$lon),] |> 
  select(canton, lon)

tmax_lat <- tmax[!duplicated(tmax$lat),] |> 
  select(canton, lat)

tmax_lon_lat <- left_join(tmax_lon, tmax_lat, by = "canton") |> 
   mutate(canton = toupper(canton)) |> 
   mutate(canton = chartr("áéíóúñÁÉÍÓÚ", "aeiounAEIOU", canton)) 
```

```{r}
# Merge to obtain a database that contains the canton code as ID, the latitude and the longitude, plus the values for the variable
tmax_weekly <- left_join(tmax_weekly_site, codes, by = "canton") |> 
  left_join(tmax_lon_lat, by = "canton") |> 
  select(-c(year, week1, canton))
```

```{r}
# Impute mean tmax
for (i in 1:312) {
  curr_week = unique(tmax_weekly$week)[i]
  df_int <- tmax_weekly |> 
  filter(week == curr_week)

  coop <- st_as_sf(df_int, coords = c("lon", "lat"), crs = 4326)

  coop <- coop |> 
    filter(ID == 607) |> 
    select(tmax_mean, ID)

  tmax_ap <- df_int |> 
    filter(!is.na(tmax_mean))|> 
    st_as_sf(coords = c("lon", "lat"), crs = 4326, remove = FALSE) 

  res <- gstat(formula = tmax_mean ~ 1, locations = tmax_ap, nmax = 5, set = list(idp = 0))

  golfito <- predict(res, coop, debug.level = 0)

  tmax_weekly$tmax_mean[tmax_weekly$week == curr_week & tmax_weekly$ID == 607] =   golfito$var1.pred
}

tmax_weekly = tmax_weekly |> 
  select(tmax_mean, week, ID)
```

```{r}
#para_eda(tmax_weekly, "tmax_min")

#para_eda(tmax_weekly, "tmax_max")

para_eda(tmax_weekly, "tmax_mean")

#para_eda(tmax_weekly, "tmax_median")
```

```{r}
# Convert the dataset to week-canton pairs as rows to be able to integrate each variable with the rest of the full database
tmax_weekly <- tmax_weekly  |> 
  mutate(week_canton = paste(week, ID, sep = "-")) |> 
  select(tmax_mean, week_canton)
```

```{r}
write.csv(tmax_weekly, file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/clean/tmax_weekly.csv")
```

## Temp min

```{r}
setwd("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/chirts/chirts_min")

tmin <- read.csv(file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/chirts/chirts_min/chirts_min.csv")
```

```{r}
tmin$time = ymd(tmin$time)
```

```{r}
# Aggregate tmin weekly with mean
tmin_weekly_site <- tmin |> 
  group_by(canton, year = isoyear(time), week1 = isoweek(time)) |>
  summarise(tmin_mean = mean(temp),
    .groups = "drop" )  |> 
  mutate(week = paste(year, week1, sep = "-")) |> 
  filter(!grepl("-53$", week)) |> 
  filter(!grepl("2026", week))
```

```{r}
# Load file that contains canton names and codes to add canton codes to tmax database
codes <- read_excel("C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/raw/dengue_limpio.xlsx")

codes <- codes |> 
  select(ID, "PROVINCIA Y CANTON") |> 
  filter(ID >= 101)

colnames(codes) = c("ID", "canton")

codes[11, "canton"] = "VAZQUEZ DE CORONADO"
codes[20, "canton"] = "LEON CORTES CASTRO"
codes[31, "canton"] = "ZARCERO"
codes[32, "canton"] = "SARCHI"
```


```{r}
# Standardize canton name in dataset so it is ready to be merged
tmin_weekly_site <- tmin_weekly_site |> 
   mutate(canton = toupper(canton)) |> 
   mutate(canton = chartr("áéíóúñÁÉÍÓÚ", "aeiounAEIOU", canton)) 
```

```{r}
# Add latitude and longitude so the data can be imputed spatially
tmin_lon <- tmin[!duplicated(tmin$lon),] |> 
  select(canton, lon)

tmin_lat <- tmin[!duplicated(tmin$lat),] |> 
  select(canton, lat)

tmin_lon_lat <- left_join(tmin_lon, tmin_lat, by = "canton") |> 
   mutate(canton = toupper(canton)) |> 
   mutate(canton = chartr("áéíóúñÁÉÍÓÚ", "aeiounAEIOU", canton)) 
```

```{r}
# Merge to obtain a database that contains the canton code as ID, the latitude and the longitude, plus the values for the variable
tmin_weekly <- left_join(tmin_weekly_site, codes, by = "canton") |> 
  left_join(tmin_lon_lat, by = "canton") |> 
  select(-c(year, week1, canton))
```

```{r}
# Impute mean tmax
for (i in 1:312) {
  curr_week = unique(tmin_weekly$week)[i]
  df_int <- tmin_weekly |> 
  filter(week == curr_week)

  coop <- st_as_sf(df_int, coords = c("lon", "lat"), crs = 4326)

  coop <- coop |> 
    filter(ID == 607) |> 
    select(tmin_mean, ID)

  tmin_ap <- df_int |> 
    filter(!is.na(tmin_mean))|> 
    st_as_sf(coords = c("lon", "lat"), crs = 4326, remove = FALSE) 

  res <- gstat(formula = tmin_mean ~ 1, locations = tmin_ap, nmax = 5, set = list(idp = 0))

  golfito <- predict(res, coop, debug.level = 0)

  tmin_weekly$tmin_mean[tmin_weekly$week == curr_week & tmin_weekly$ID == 607] =   golfito$var1.pred
}

tmin_weekly = tmin_weekly |> 
  select(tmin_mean, week, ID)
```

```{r}
# Create weekly mean temperature in tmin_weekly dataset. This could have also been added to tmax_weekly, as it will be saved in a different dataset from tmax_mean and tmin_mean
tmin_weekly$temp_prom <- (tmax_mean$tmax_mean + tmin_weekly$tmin_mean) / 2
```

```{r}
#para_eda(tmin_weekly, "tmin_min")

#para_eda(tmin_weekly, "tmin_min")

para_eda(tmin_weekly, "tmin_mean")

para_eda(tmin_weekly, "temp_prom")

#para_eda(tmin_weekly, "tmin_median")
```

```{r}
# Convert the dataset to week-canton pairs as rows to be able to integrate each variable with the rest of the full database
tmin_mean <- tmin_weekly  |> 
  mutate(week_canton = paste(week, ID, sep = "-")) |> 
  select(tmin_mean, week_canton)
```

```{r}
# Convert the dataset to week-canton pairs as rows to be able to integrate each variable with the rest of the full database
temp_prom <- tmin_weekly |> 
  mutate(week_canton = paste(week, ID, sep = "-")) |> 
  select(temp_prom, week_canton)
```

```{r}
write.csv(tmin_mean, file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/clean/tmin_weekly.csv")

write.csv(temp_prom, file = "C:/Users/nan/OneDrive - Universidad de Costa Rica/cuenta personal/ucr pers/practica profesional/practica dengue/dengue-model/data/clean/temp_prom.csv")
```









